version: "3.9"

services:

  traefik:
    container_name: "scsa.traefik"
    image: traefik:v1.7
    command: --api --docker --web
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - traefik.port=8080 # web ui (enabled by --api)
      - traefik.frontend.rule=Host:monitor.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apache:
    container_name: "scsa.wp"
    image: wodby/php-apache
    labels:
      - traefik.frontend.rule=Host:wp.localhost
      - traefik.backend=scsa.wp
    depends_on:
      - "traefik"
    ports:
      - "80"
    environment:
      APACHE_BACKEND_HOST: php
      APACHE_BACKEND_PORT: 9000
      APACHE_DIRECTORY_INDEX: index.php
      APACHE_SERVER_NAME: wp.localhost
      APACHE_SERVER_ROOT: /var/www/wordpress
    volumes:
      - ./wordpress:/var/www/wordpress

  mysql:
    container_name: "scsa.mysql"
    image: wodby/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scsa
      MYSQL_PASSWORD: scsa
      MYSQL_DATABASE: scsa

  phpmyadmin:
    container_name: "scsa.phpmyadmin"
    image: "phpmyadmin/phpmyadmin"
    labels:
      - traefik.frontend.rule=Host:pma.localhost
    depends_on:
      - "traefik"
      - "mysql"
    environment:
      PMA_HOST: "mysql"
    expose:
      - "80"
 

 
