version: "3.9"

services:

  traefik:
    container_name: "scsa.traefik"
    image: traefik:v1.7
    command: --api --docker --web
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - traefik.port=8080 # web ui (enabled by --api)
      - traefik.frontend.rule=Host:monitor.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apache:
    container_name: "scsa.test"
    image: httpd
    labels:
      - traefik.frontend.rule=Host:test.localhost
      - traefik.backend=scsa.test
    depends_on:
      - "traefik"
    ports:
      - "80"
    volumes:
      - ./apache/index.html:/usr/local/apache2/htdocs/index.html

  nginx:
    container_name: "scsa.website"
    image: nginx
    labels:
      - traefik.frontend.rule=Host:scsa.localhost
      - traefik.backend=scsa.website
    depends_on:
      - "traefik"
    expose:
      - "80"
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html

  mysql:
    container_name: "scsa.mysql"
    image: wodby/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scsa
      MYSQL_PASSWORD: scsa
      MYSQL_DATABASE: scsa

  phpmyadmin:
    container_name: "scsa.phpmyadmin"
    image: "phpmyadmin/phpmyadmin"
    labels:
      - traefik.frontend.rule=Host:pma.localhost
    depends_on:
      - "traefik"
      - "mysql"
    environment:
      PMA_HOST: "mysql"
    expose:
      - "80"
 

 
