version: "3.9"

services:

  traefik:
    container_name: "scsa.traefik"
    image: traefik:v1.7
    command: --api --docker --web
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - traefik.port=8080 # web ui (enabled by --api)
      - traefik.frontend.rule=Host:monitor.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: wodby/nginx
    labels:
      - traefik.frontend.rule=Host:wp.local
      - traefik.backend=scsa.wp
    container_name: "scsa.nginx"
    depends_on:
      - "php"
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
      #NGINX_SERVER_ROOT: /var/www/html/subdir
    volumes:
      - ./wordpress:/var/www/html:cached

  php:
    image: wodby/wordpress-php
    container_name: "scsa.php"
    depends_on:
      - "mysql"
    volumes:
      - ./wordpress:/var/www/html:cached

  mysql:
    container_name: "scsa.mysql"
    image: wodby/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scsa
      MYSQL_PASSWORD: scsa
      MYSQL_DATABASE: scsa
    expose:
      - "3306"

  phpmyadmin:
    container_name: "scsa.phpmyadmin"
    image: "phpmyadmin/phpmyadmin"
    labels:
      - traefik.frontend.rule=Host:pma.local
    depends_on:
      - "traefik"
      - "mysql"
    environment:
      PMA_HOST: "mysql"
    expose:
      - "80"
 

 
